#!/usr/bin/perl

use strict;
use warnings;

use Debian::DEP12;

@ARGV = ( '-' ) unless @ARGV;

for my $i (0..$#ARGV) {
    my $filename = $ARGV[$i];
    open( my $inp, '<' . $filename );
    my $yaml = join '', <$inp>;
    close $inp;

    eval {
        local $SIG{__WARN__} = sub {
            print STDERR "$0: $filename: WARNING, $_[0]";
        };

        my $meta = Debian::DEP12->new( $yaml );
        $meta->validate;
    };
    if( $@ ) {
        print STDERR "$0: $filename: ERROR, $@";
    }
}
